#!/usr/bin/env python3
"""
Mockup Generator for Lead Outreach
===================================
Generates personalized website mockups and outreach messages for leads without websites.
Uses Astro templates, Claude API for content generation, and Playwright for screenshots.

Usage:
    python mockup-generator.py

Requirements:
    - Python 3.10+
    - Node.js 18+ (for Astro)
    - See requirements.txt for Python dependencies
    - Run: playwright install chromium
"""

# =============================================================================
# SECTION 1: IMPORTS AND CONSTANTS
# =============================================================================

import os
import sys
import json
import re
import shutil
import signal
import subprocess
import time
import asyncio
import logging
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass, field, asdict
from typing import Optional, List, Dict, Literal, Any, Tuple
from urllib.parse import urlparse
import unicodedata
from concurrent.futures import ThreadPoolExecutor, as_completed
from threading import Lock, Semaphore
from queue import Queue

# Third-party imports
import anthropic
import pandas as pd
import httpx
import psutil
from PIL import Image
from dotenv import load_dotenv

# Playwright (async)
from playwright.async_api import async_playwright

# Instagram scraping
import instaloader

# GUI
import tkinter as tk
from tkinter import filedialog, messagebox, ttk

# Progress tracking
from tqdm import tqdm

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler('mockup-generator.log', encoding='utf-8')
    ]
)
logger = logging.getLogger(__name__)

# =============================================================================
# CONSTANTS
# =============================================================================

THEMES = ['elegante', 'fresh', 'bold', 'natural']
DEFAULT_PORT = 4321
SERVER_START_TIMEOUT = 120  # seconds
NPM_INSTALL_TIMEOUT = 300  # seconds
SCREENSHOT_WAIT = 3000  # milliseconds

# Rate limiting delays (seconds)
RATE_LIMITS = {
    'instagram': 5.0,
    'google': 2.0,
    'unsplash': 1.0,
    'claude': 0.5
}

# Default sections in order
DEFAULT_SECTIONS = [
    'Hero', 'About', 'Services', 'Gallery',
    'Testimonials', 'Contact', 'Footer', 'WhatsAppButton'
]

# Required sections (cannot be hidden)
REQUIRED_SECTIONS = ['Hero', 'Contact', 'Footer', 'WhatsAppButton']

# Parallel processing
DEFAULT_WORKERS = 3
MAX_WORKERS = 5
PORT_POOL = [4321, 4322, 4323, 4324, 4325]  # Ports for parallel Astro servers

# =============================================================================
# SECTION 2: DATA CLASSES
# =============================================================================

@dataclass
class Lead:
    """Represents a lead from the Excel file."""
    business_name: str
    niche: str
    pais: str
    region: str
    ciudad: str
    comuna: str
    website_url: str
    phone_whatsapp: str
    instagram_fb_link: str
    status: str
    tech_flaw: str
    owner_name: str
    tier: str
    source_query: str
    generate_mockup: str
    mockup_status: str
    mockup_path: str
    mockup_date: Optional[datetime]
    row_index: int  # Excel row for updates (0-indexed from data, not header)


@dataclass
class Template:
    """Represents a discovered template."""
    name: str
    path: Path
    niche: str
    description: str


@dataclass
class DesignDecisions:
    """Claude's design decisions for a lead."""
    template_name: str
    theme: Literal['elegante', 'fresh', 'bold', 'natural']
    sections_order: List[str]
    sections_to_hide: List[str]


@dataclass
class ImageSource:
    """Represents a sourced image."""
    url: str
    local_path: Path
    source_type: Literal['instagram', 'google', 'unsplash', 'placeholder']
    alt_text: str


@dataclass
class GeneratedContent:
    """All content generated by Claude for a site."""
    business_name: str
    tagline: str
    description: str
    hero_title: str
    hero_subtitle: str
    hero_cta_primary: str
    hero_cta_secondary: str
    about_title: str
    about_name: str
    about_bio: str
    about_badges: List[Dict[str, str]]
    services: List[Dict[str, Any]]
    gallery_title: str
    testimonials: List[Dict[str, Any]]
    contact_schedule: Dict[str, str]
    seo_keywords: str


@dataclass
class ProcessingResult:
    """Result of processing a single lead."""
    success: bool
    lead: Lead
    output_path: Optional[Path] = None
    error_message: Optional[str] = None


# =============================================================================
# SECTION 3: GUI DIALOG FUNCTIONS
# =============================================================================

def init_tkinter() -> tk.Tk:
    """Initialize tkinter root window (hidden)."""
    root = tk.Tk()
    root.withdraw()
    root.attributes('-topmost', True)
    return root


def select_excel_file() -> Optional[Path]:
    """
    Opens file dialog to select Excel file with leads.
    Returns None if cancelled.
    """
    root = init_tkinter()

    file_path = filedialog.askopenfilename(
        title="Selecciona el archivo Excel con leads",
        filetypes=[
            ("Excel files", "*.xlsx *.xls"),
            ("All files", "*.*")
        ],
        parent=root
    )

    root.destroy()

    if file_path:
        return Path(file_path)
    return None


def select_templates_folder() -> Optional[Path]:
    """
    Opens folder dialog to select templates root folder.
    Returns None if cancelled.
    """
    root = init_tkinter()

    folder_path = filedialog.askdirectory(
        title="Selecciona la carpeta de templates",
        parent=root
    )

    root.destroy()

    if folder_path:
        path = Path(folder_path)
        # Basic validation - check if it has subfolders
        subfolders = [d for d in path.iterdir() if d.is_dir() and not d.name.startswith('.')]
        if not subfolders:
            messagebox.showwarning(
                "Advertencia",
                "La carpeta seleccionada no parece contener templates.\n"
                "Asegúrate de que tenga subcarpetas de nichos (ej: manicuristas/)"
            )
        return path
    return None


def select_output_folder() -> Optional[Path]:
    """
    Opens folder dialog to select output folder.
    Creates folder if it doesn't exist.
    Returns None if cancelled.
    """
    root = init_tkinter()

    folder_path = filedialog.askdirectory(
        title="Selecciona la carpeta de salida para mockups",
        parent=root
    )

    root.destroy()

    if folder_path:
        path = Path(folder_path)
        path.mkdir(parents=True, exist_ok=True)
        return path
    return None


def show_confirmation(message: str, title: str = "Confirmación") -> bool:
    """Show confirmation dialog and return True if user confirms."""
    root = init_tkinter()
    result = messagebox.askyesno(title, message, parent=root)
    root.destroy()
    return result


def show_error(message: str, title: str = "Error"):
    """Show error dialog."""
    root = init_tkinter()
    messagebox.showerror(title, message, parent=root)
    root.destroy()


def show_info(message: str, title: str = "Información"):
    """Show info dialog."""
    root = init_tkinter()
    messagebox.showinfo(title, message, parent=root)
    root.destroy()


@dataclass
class ProcessingConfig:
    """Configuration for processing from GUI."""
    num_workers: int = DEFAULT_WORKERS
    use_parallel: bool = True
    confirmed: bool = False


def show_config_dialog(
    leads_count: int,
    templates_count: int,
    output_folder: Path
) -> Optional[ProcessingConfig]:
    """
    Shows configuration dialog with worker slider and processing options.
    Returns ProcessingConfig or None if cancelled.
    """
    config = ProcessingConfig()

    root = tk.Tk()
    root.title("Configuración de Procesamiento")
    root.geometry("450x400")
    root.resizable(False, False)

    # Center window
    root.eval('tk::PlaceWindow . center')

    # Make window stay on top
    root.attributes('-topmost', True)

    # Main frame with padding
    main_frame = ttk.Frame(root, padding="20")
    main_frame.pack(fill=tk.BOTH, expand=True)

    # Title
    title_label = ttk.Label(
        main_frame,
        text="Mockup Generator",
        font=('Helvetica', 16, 'bold')
    )
    title_label.pack(pady=(0, 15))

    # Summary frame
    summary_frame = ttk.LabelFrame(main_frame, text="Resumen", padding="10")
    summary_frame.pack(fill=tk.X, pady=(0, 15))

    ttk.Label(summary_frame, text=f"Leads a procesar: {leads_count}").pack(anchor=tk.W)
    ttk.Label(summary_frame, text=f"Templates disponibles: {templates_count}").pack(anchor=tk.W)
    ttk.Label(summary_frame, text=f"Carpeta de salida: {output_folder}").pack(anchor=tk.W)

    # Workers frame
    workers_frame = ttk.LabelFrame(main_frame, text="Procesamiento Paralelo", padding="10")
    workers_frame.pack(fill=tk.X, pady=(0, 15))

    # Parallel processing checkbox
    parallel_var = tk.BooleanVar(value=True)

    def toggle_parallel():
        if parallel_var.get():
            workers_slider.config(state=tk.NORMAL)
            workers_label.config(text=f"Workers: {workers_var.get()}")
        else:
            workers_slider.config(state=tk.DISABLED)
            workers_label.config(text="Workers: 1 (secuencial)")

    parallel_check = ttk.Checkbutton(
        workers_frame,
        text="Habilitar procesamiento paralelo",
        variable=parallel_var,
        command=toggle_parallel
    )
    parallel_check.pack(anchor=tk.W, pady=(0, 10))

    # Workers slider
    workers_var = tk.IntVar(value=DEFAULT_WORKERS)
    workers_label = ttk.Label(workers_frame, text=f"Workers: {DEFAULT_WORKERS}")
    workers_label.pack(anchor=tk.W)

    def update_workers_label(val):
        workers_label.config(text=f"Workers: {int(float(val))}")

    workers_slider = ttk.Scale(
        workers_frame,
        from_=1,
        to=MAX_WORKERS,
        orient=tk.HORIZONTAL,
        variable=workers_var,
        command=update_workers_label
    )
    workers_slider.pack(fill=tk.X, pady=(5, 5))

    workers_hint = ttk.Label(
        workers_frame,
        text="Más workers = más rápido, pero más uso de recursos",
        font=('Helvetica', 9),
        foreground='gray'
    )
    workers_hint.pack(anchor=tk.W)

    # Estimated time
    est_time = leads_count * 2  # ~2 min per lead with default workers
    if parallel_var.get():
        est_time = est_time // DEFAULT_WORKERS
    est_label = ttk.Label(
        main_frame,
        text=f"Tiempo estimado: ~{est_time} minutos",
        font=('Helvetica', 10)
    )
    est_label.pack(pady=(0, 15))

    # Buttons frame
    buttons_frame = ttk.Frame(main_frame)
    buttons_frame.pack(fill=tk.X, pady=(10, 0))

    def on_confirm():
        config.num_workers = int(workers_var.get())
        config.use_parallel = parallel_var.get()
        config.confirmed = True
        root.destroy()

    def on_cancel():
        config.confirmed = False
        root.destroy()

    cancel_btn = ttk.Button(buttons_frame, text="Cancelar", command=on_cancel)
    cancel_btn.pack(side=tk.LEFT, padx=(0, 10))

    confirm_btn = ttk.Button(
        buttons_frame,
        text="Iniciar Procesamiento",
        command=on_confirm
    )
    confirm_btn.pack(side=tk.RIGHT)

    # Handle window close
    root.protocol("WM_DELETE_WINDOW", on_cancel)

    root.mainloop()

    if config.confirmed:
        return config
    return None


# =============================================================================
# SECTION 4: TEMPLATE DISCOVERY FUNCTIONS
# =============================================================================

def validate_template_structure(template_path: Path) -> bool:
    """
    Validates that a template has the required Astro structure.
    Required: package.json, src/config/site.config.ts, src/pages/index.astro
    """
    required_files = [
        template_path / 'package.json',
        template_path / 'src' / 'config' / 'site.config.ts',
        template_path / 'src' / 'pages' / 'index.astro',
    ]

    return all(f.exists() for f in required_files)


def get_template_description(template_path: Path) -> str:
    """
    Extracts description from template's README.md if available.
    Returns template folder name if no README.
    """
    readme_path = template_path / 'README.md'

    if readme_path.exists():
        try:
            content = readme_path.read_text(encoding='utf-8')
            # Extract first paragraph after title
            lines = content.split('\n')
            description_lines = []
            in_description = False

            for line in lines:
                if line.startswith('#') and not in_description:
                    in_description = True
                    continue
                if in_description:
                    if line.startswith('#'):
                        break
                    if line.strip():
                        description_lines.append(line.strip())
                    if len(description_lines) >= 2:
                        break

            if description_lines:
                return ' '.join(description_lines)[:200]
        except Exception:
            pass

    return f"Template: {template_path.name}"


def discover_templates(templates_folder: Path) -> Dict[str, List[Template]]:
    """
    Scans templates folder and returns dict mapping tipo -> list of templates.

    Supports multiple structures:
    - Flat: templates/variacion-1/ (has package.json)
    - 2-level: templates/tipo/variacion/ (tipo/variacion has package.json)
    - 3-level: templates/niche/tipo/variacion/ (variacion has package.json)

    Examples:
    - templates/variacion-1/ → flat (tipo = "default")
    - templates/template-1-independiente/variacion-1/ → 2-level
    - manicuristas/template-1-independiente/variacion-1/ → when selecting manicuristas/
    """
    templates_by_tipo: Dict[str, List[Template]] = {}

    if not templates_folder.exists():
        logger.error(f"Templates folder does not exist: {templates_folder}")
        return templates_by_tipo

    def add_template(path: Path, tipo: str, niche: str = ""):
        """Helper to add a validated template."""
        if tipo not in templates_by_tipo:
            templates_by_tipo[tipo] = []

        # Build descriptive name
        if tipo != "default":
            name = f"{tipo}/{path.name}"
        else:
            name = path.name

        template = Template(
            name=name,
            path=path,
            niche=niche or tipo,
            description=get_template_description(path)
        )
        templates_by_tipo[tipo].append(template)
        logger.info(f"Found template: {tipo}/{path.name}")

    def scan_directory(directory: Path, tipo: str = "", niche: str = ""):
        """Recursively scan for valid templates up to 3 levels deep."""
        for item in directory.iterdir():
            if not item.is_dir() or item.name.startswith('.'):
                continue

            if validate_template_structure(item):
                # Found a valid template
                effective_tipo = tipo or "default"
                add_template(item, effective_tipo, niche)
            else:
                # Not a template, check subdirectories
                if not tipo:
                    # This could be a "tipo" folder (e.g., template-1-independiente)
                    for subitem in item.iterdir():
                        if subitem.is_dir() and not subitem.name.startswith('.'):
                            if validate_template_structure(subitem):
                                # Found: tipo/variacion
                                add_template(subitem, item.name, niche)
                            else:
                                # Could be: niche/tipo/variacion (3 levels)
                                for deep_item in subitem.iterdir():
                                    if deep_item.is_dir() and validate_template_structure(deep_item):
                                        add_template(deep_item, subitem.name, item.name)

    scan_directory(templates_folder)
    return templates_by_tipo


# =============================================================================
# SECTION 5: CLAUDE API INTEGRATION
# =============================================================================

def create_claude_client() -> anthropic.Anthropic:
    """
    Creates Anthropic client from environment variable.
    Raises EnvironmentError if API key not set.
    """
    api_key = os.getenv('ANTHROPIC_API_KEY')

    if not api_key:
        raise EnvironmentError(
            "ANTHROPIC_API_KEY not set. "
            "Copy .env.example to .env and add your API key."
        )

    return anthropic.Anthropic(api_key=api_key)


def choose_design_decisions(
    client: anthropic.Anthropic,
    lead: Lead,
    available_templates: List[Template]
) -> DesignDecisions:
    """
    Uses Claude to choose template, theme, and section configuration.
    """
    # Build template descriptions
    template_descriptions = "\n".join([
        f"- {t.name}: {t.description}"
        for t in available_templates
    ])

    prompt = f"""Eres un experto en diseño web eligiendo la mejor configuración de sitio para un negocio.

INFORMACIÓN DEL NEGOCIO:
- Nombre: {lead.business_name}
- Nicho: {lead.niche}
- Ubicación: {lead.comuna}, {lead.ciudad or lead.region}
- Instagram: {lead.instagram_fb_link or 'No disponible'}
- Teléfono: {lead.phone_whatsapp or 'No disponible'}

TEMPLATES DISPONIBLES PARA {lead.niche.upper()}:
{template_descriptions}

TEMAS DE COLOR DISPONIBLES:
- elegante: Rosa pálido + Dorado - Para negocios premium y sofisticados
- fresh: Mint + Coral - Para negocios jóvenes y modernos
- bold: Negro + Fucsia - Para artistas atrevidas y creativas
- natural: Verde Sage + Beige - Para negocios eco-friendly y naturales

SECCIONES DISPONIBLES (en orden default):
Hero, About, Services, Gallery, Testimonials, Contact, Footer, WhatsAppButton

REGLAS:
1. Hero, Contact, Footer y WhatsAppButton son OBLIGATORIOS y no pueden ocultarse
2. WhatsAppButton siempre debe ir al final
3. Si no hay Instagram disponible, considera ocultar Gallery o usar menos imágenes
4. Si no hay reseñas/testimonios, oculta la sección Testimonials
5. Elige el tema según el estilo del negocio y su audiencia target

Responde SOLO con un JSON válido (sin markdown, sin explicaciones):
{{
    "template_name": "nombre-exacto-del-template",
    "theme": "elegante|fresh|bold|natural",
    "sections_order": ["Hero", "About", "Services", "Gallery", "Contact", "Footer", "WhatsAppButton"],
    "sections_to_hide": ["Testimonials"]
}}"""

    try:
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=500,
            messages=[{"role": "user", "content": prompt}]
        )

        response_text = message.content[0].text.strip()

        # Clean potential markdown formatting
        if response_text.startswith('```'):
            response_text = re.sub(r'^```\w*\n?', '', response_text)
            response_text = re.sub(r'\n?```$', '', response_text)

        data = json.loads(response_text)

        # Validate template name
        valid_names = [t.name for t in available_templates]
        if data['template_name'] not in valid_names:
            logger.warning(f"Claude chose invalid template '{data['template_name']}', using first available")
            data['template_name'] = valid_names[0] if valid_names else 'template-1-independiente'

        # Validate theme
        if data['theme'] not in THEMES:
            data['theme'] = 'elegante'

        # Ensure required sections are not hidden
        data['sections_to_hide'] = [
            s for s in data.get('sections_to_hide', [])
            if s not in REQUIRED_SECTIONS
        ]

        return DesignDecisions(
            template_name=data['template_name'],
            theme=data['theme'],
            sections_order=data.get('sections_order', DEFAULT_SECTIONS),
            sections_to_hide=data.get('sections_to_hide', [])
        )

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse Claude response: {e}")
        # Return defaults
        return DesignDecisions(
            template_name=available_templates[0].name if available_templates else 'template-1-independiente',
            theme='elegante',
            sections_order=DEFAULT_SECTIONS,
            sections_to_hide=['Testimonials']
        )
    except Exception as e:
        logger.error(f"Claude API error: {e}")
        raise


def generate_personalized_content(
    client: anthropic.Anthropic,
    lead: Lead,
    design_decisions: DesignDecisions,
    instagram_context: Optional[str] = None
) -> GeneratedContent:
    """
    Uses Claude to generate all personalized content for the site.
    """
    instagram_section = ""
    if instagram_context:
        instagram_section = f"""
CONTEXTO DE INSTAGRAM (usa esto para el tono y estilo):
{instagram_context[:500]}
"""

    prompt = f"""Genera contenido de sitio web en español chileno para este negocio.

INFORMACIÓN DEL NEGOCIO:
- Nombre: {lead.business_name}
- Dueño/a: {lead.owner_name or 'No especificado'}
- Nicho: {lead.niche}
- Ubicación: {lead.comuna}, {lead.ciudad or lead.region}
- Teléfono: {lead.phone_whatsapp}
- Tema elegido: {design_decisions.theme}
{instagram_section}

Genera un JSON con TODO este contenido (usa español chileno natural):

{{
    "business_name": "{lead.business_name}",
    "tagline": "Tagline corto y memorable (max 50 caracteres)",
    "description": "Meta descripción SEO (max 160 caracteres)",
    "hero_title": "Título hero impactante",
    "hero_subtitle": "Subtítulo con referencia a {lead.comuna}",
    "hero_cta_primary": "Texto botón principal (ej: Agenda tu Hora)",
    "hero_cta_secondary": "Texto botón secundario (ej: Ver Trabajos)",
    "about_title": "Título sección about",
    "about_name": "{lead.owner_name or lead.business_name}",
    "about_bio": "Bio profesional 2-3 oraciones",
    "about_badges": [
        {{"icon": "emoji", "text": "texto badge"}},
        {{"icon": "emoji", "text": "texto badge"}},
        {{"icon": "emoji", "text": "texto badge"}},
        {{"icon": "emoji", "text": "texto badge"}}
    ],
    "services": [
        {{
            "name": "Nombre servicio",
            "description": "Descripción breve",
            "price": "XX.XXX",
            "duration": "XX min",
            "popular": true/false
        }}
    ],
    "gallery_title": "Título galería",
    "testimonials": [],
    "contact_schedule": {{
        "weekdays": "Lun - Vie: 10:00 - 20:00",
        "saturday": "Sábado: 10:00 - 18:00",
        "sunday": "Domingo: Cerrado"
    }},
    "seo_keywords": "palabras clave separadas por coma para {lead.niche} en {lead.comuna}"
}}

IMPORTANTE:
- Genera 4-6 servicios realistas para {lead.niche}
- Precios en CLP (pesos chilenos) sin decimales
- Usa términos chilenos (hora, no cita)
- Marca 1-2 servicios como "popular": true
- Si no hay testimonios, deja el array vacío

Responde SOLO con el JSON, sin markdown ni explicaciones."""

    try:
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=2000,
            messages=[{"role": "user", "content": prompt}]
        )

        response_text = message.content[0].text.strip()

        # Clean markdown
        if response_text.startswith('```'):
            response_text = re.sub(r'^```\w*\n?', '', response_text)
            response_text = re.sub(r'\n?```$', '', response_text)

        data = json.loads(response_text)

        return GeneratedContent(
            business_name=data.get('business_name', lead.business_name),
            tagline=data.get('tagline', f'{lead.niche} en {lead.comuna}'),
            description=data.get('description', ''),
            hero_title=data.get('hero_title', 'Bienvenido'),
            hero_subtitle=data.get('hero_subtitle', ''),
            hero_cta_primary=data.get('hero_cta_primary', 'Contactar'),
            hero_cta_secondary=data.get('hero_cta_secondary', 'Ver más'),
            about_title=data.get('about_title', 'Sobre Nosotros'),
            about_name=data.get('about_name', lead.owner_name or lead.business_name),
            about_bio=data.get('about_bio', ''),
            about_badges=data.get('about_badges', []),
            services=data.get('services', []),
            gallery_title=data.get('gallery_title', 'Nuestros Trabajos'),
            testimonials=data.get('testimonials', []),
            contact_schedule=data.get('contact_schedule', {}),
            seo_keywords=data.get('seo_keywords', '')
        )

    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse Claude content response: {e}")
        raise
    except Exception as e:
        logger.error(f"Claude API error generating content: {e}")
        raise


def generate_outreach_messages(
    client: anthropic.Anthropic,
    lead: Lead,
    mockup_filename: str
) -> Dict[str, str]:
    """
    Generates WhatsApp and Email outreach messages.
    """
    prompt = f"""Genera mensajes de outreach para este lead potencial.

CONTEXTO:
- Negocio: {lead.business_name}
- Dueño/a: {lead.owner_name or 'el/la dueño/a'}
- Ubicación: {lead.comuna}, {lead.ciudad or lead.region}
- No tienen sitio web actualmente
- Les creamos un mockup/preview de cómo podría verse su sitio
- El mockup está en el archivo: {mockup_filename}

Genera DOS mensajes en español chileno:

1. MENSAJE WHATSAPP:
- Tono casual y amigable
- Usa emojis de forma natural (no excesiva)
- Máximo 500 caracteres
- Menciona que vimos su negocio y creamos algo especial
- Incluye soft CTA (sin presión)

2. MENSAJE EMAIL:
- Tono profesional pero cercano
- Incluye línea de asunto atractiva
- 150-200 palabras
- Estructura: saludo, propuesta de valor, mencionar mockup, CTA
- Firma con "Equipo Ahjin"

Responde en este formato exacto:

WHATSAPP:
[mensaje aquí]

EMAIL:
Asunto: [asunto aquí]

[cuerpo del email aquí]"""

    try:
        message = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1000,
            messages=[{"role": "user", "content": prompt}]
        )

        response_text = message.content[0].text.strip()

        # Parse response
        whatsapp_msg = ""
        email_msg = ""

        parts = response_text.split("EMAIL:")
        if len(parts) >= 2:
            whatsapp_part = parts[0]
            email_part = parts[1]

            # Extract WhatsApp message
            if "WHATSAPP:" in whatsapp_part:
                whatsapp_msg = whatsapp_part.split("WHATSAPP:")[1].strip()
            else:
                whatsapp_msg = whatsapp_part.strip()

            email_msg = email_part.strip()
        else:
            # Fallback
            whatsapp_msg = response_text
            email_msg = response_text

        return {
            'whatsapp': whatsapp_msg,
            'email': email_msg
        }

    except Exception as e:
        logger.error(f"Claude API error generating messages: {e}")
        # Return default messages
        return {
            'whatsapp': f"Hola! 👋 Vi {lead.business_name} y me encantó. Te preparé algo especial - un preview de cómo podría verse tu sitio web. ¿Te gustaría verlo?",
            'email': f"Asunto: Una propuesta especial para {lead.business_name}\n\nHola,\n\nVi tu negocio y me pareció increíble. Te preparé un mockup de cómo podría verse tu sitio web.\n\nSaludos,\nEquipo Ahjin"
        }


# =============================================================================
# SECTION 6: IMAGE SOURCING
# =============================================================================

class RateLimiter:
    """Simple rate limiter for API calls."""

    def __init__(self):
        self.last_call_times: Dict[str, float] = {}

    def wait_if_needed(self, service: str):
        """Blocks until rate limit allows next request."""
        delay = RATE_LIMITS.get(service, 1.0)
        last_call = self.last_call_times.get(service, 0)
        elapsed = time.time() - last_call

        if elapsed < delay:
            time.sleep(delay - elapsed)

        self.last_call_times[service] = time.time()


class ImageSourcer:
    """Handles image sourcing with fallback chain."""

    def __init__(
        self,
        unsplash_key: Optional[str] = None,
        fallback_folder: Optional[Path] = None
    ):
        self.unsplash_key = unsplash_key or os.getenv('UNSPLASH_ACCESS_KEY')
        self.fallback_folder = fallback_folder or Path(__file__).parent / 'fallback_images'
        self.rate_limiter = RateLimiter()
        self.session = httpx.Client(timeout=30.0, follow_redirects=True)
        self._instaloader: Optional[instaloader.Instaloader] = None

    @property
    def instaloader(self) -> instaloader.Instaloader:
        """Lazy-load instaloader instance."""
        if self._instaloader is None:
            self._instaloader = instaloader.Instaloader(
                download_videos=False,
                download_video_thumbnails=False,
                download_geotags=False,
                download_comments=False,
                save_metadata=False,
                compress_json=False,
                quiet=True
            )
        return self._instaloader

    def source_images_for_lead(
        self,
        lead: Lead,
        output_dir: Path,
        count: int = 6
    ) -> List[ImageSource]:
        """
        Attempts to source images in priority order.
        Returns list of ImageSource with local paths.
        """
        images: List[ImageSource] = []

        # Ensure output directory exists
        images_dir = output_dir / 'images'
        images_dir.mkdir(parents=True, exist_ok=True)

        # 1. Try Instagram
        if lead.instagram_fb_link:
            logger.info(f"Attempting Instagram scrape for {lead.business_name}")
            try:
                instagram_images = self.scrape_instagram(
                    lead.instagram_fb_link,
                    images_dir,
                    count
                )
                images.extend(instagram_images)
                logger.info(f"Got {len(instagram_images)} images from Instagram")
            except Exception as e:
                logger.warning(f"Instagram scraping failed: {e}")

        # 2. Try Unsplash if we need more images
        remaining = count - len(images)
        if remaining > 0 and self.unsplash_key:
            logger.info(f"Fetching {remaining} images from Unsplash")
            try:
                unsplash_images = self.fetch_unsplash_images(
                    lead.niche,
                    images_dir,
                    remaining,
                    offset=len(images)
                )
                images.extend(unsplash_images)
            except Exception as e:
                logger.warning(f"Unsplash fetch failed: {e}")

        # 3. Use placeholders for any remaining
        remaining = count - len(images)
        if remaining > 0:
            logger.info(f"Using {remaining} placeholder images")
            placeholder_images = self.get_placeholder_images(
                lead.niche,
                images_dir,
                remaining,
                offset=len(images)
            )
            images.extend(placeholder_images)

        return images

    def scrape_instagram(
        self,
        instagram_url: str,
        output_dir: Path,
        count: int = 6
    ) -> List[ImageSource]:
        """
        Scrapes recent posts from Instagram profile.
        """
        images: List[ImageSource] = []

        # Extract username from URL
        username = self._extract_instagram_username(instagram_url)
        if not username:
            logger.warning(f"Could not extract username from: {instagram_url}")
            return images

        try:
            self.rate_limiter.wait_if_needed('instagram')
            profile = instaloader.Profile.from_username(
                self.instaloader.context,
                username
            )

            if profile.is_private:
                logger.warning(f"Instagram profile @{username} is private")
                return images

            # Download posts
            for i, post in enumerate(profile.get_posts()):
                if i >= count:
                    break

                try:
                    self.rate_limiter.wait_if_needed('instagram')

                    # Get image URL
                    image_url = post.url

                    # Download image
                    response = self.session.get(image_url)
                    response.raise_for_status()

                    # Save image
                    filename = f"instagram_{i + 1}.jpg"
                    filepath = output_dir / filename

                    with open(filepath, 'wb') as f:
                        f.write(response.content)

                    # Convert to JPG if needed and resize
                    self._process_image(filepath)

                    images.append(ImageSource(
                        url=image_url,
                        local_path=filepath,
                        source_type='instagram',
                        alt_text=post.caption[:50] if post.caption else f"Instagram post {i + 1}"
                    ))

                except Exception as e:
                    logger.warning(f"Failed to download Instagram post {i}: {e}")
                    continue

        except instaloader.exceptions.ProfileNotExistsException:
            logger.warning(f"Instagram profile @{username} does not exist")
        except instaloader.exceptions.ConnectionException as e:
            logger.warning(f"Instagram connection error: {e}")
        except Exception as e:
            logger.warning(f"Instagram scraping error: {e}")

        return images

    def fetch_unsplash_images(
        self,
        query: str,
        output_dir: Path,
        count: int = 6,
        offset: int = 0
    ) -> List[ImageSource]:
        """
        Fetches images from Unsplash API.
        """
        images: List[ImageSource] = []

        if not self.unsplash_key:
            return images

        # Map niche to search query
        query_map = {
            'manicuristas': 'nail art manicure nails',
            'profesionales-salud': 'healthcare medical clinic',
        }
        search_query = query_map.get(query, query)

        try:
            self.rate_limiter.wait_if_needed('unsplash')

            response = self.session.get(
                'https://api.unsplash.com/search/photos',
                params={
                    'query': search_query,
                    'per_page': count,
                    'orientation': 'landscape'
                },
                headers={
                    'Authorization': f'Client-ID {self.unsplash_key}'
                }
            )
            response.raise_for_status()

            data = response.json()

            for i, photo in enumerate(data.get('results', [])):
                try:
                    # Get regular size URL
                    image_url = photo['urls']['regular']

                    # Download
                    img_response = self.session.get(image_url)
                    img_response.raise_for_status()

                    filename = f"unsplash_{offset + i + 1}.jpg"
                    filepath = output_dir / filename

                    with open(filepath, 'wb') as f:
                        f.write(img_response.content)

                    self._process_image(filepath)

                    images.append(ImageSource(
                        url=image_url,
                        local_path=filepath,
                        source_type='unsplash',
                        alt_text=photo.get('alt_description', f'Image {offset + i + 1}')
                    ))

                except Exception as e:
                    logger.warning(f"Failed to download Unsplash image: {e}")
                    continue

        except Exception as e:
            logger.warning(f"Unsplash API error: {e}")

        return images

    def get_placeholder_images(
        self,
        niche: str,
        output_dir: Path,
        count: int = 6,
        offset: int = 0
    ) -> List[ImageSource]:
        """
        Copies placeholder images from fallback folder.
        """
        images: List[ImageSource] = []

        # Look for niche-specific placeholders
        niche_folder = self.fallback_folder / niche

        if not niche_folder.exists():
            # Try generic folder
            niche_folder = self.fallback_folder / 'generic'

        if not niche_folder.exists():
            logger.warning(f"No fallback images found for niche: {niche}")
            return images

        # Get available images
        available_images = list(niche_folder.glob('*.jpg')) + list(niche_folder.glob('*.png'))

        for i in range(count):
            if not available_images:
                break

            # Cycle through available images if needed
            source_image = available_images[i % len(available_images)]

            filename = f"placeholder_{offset + i + 1}.jpg"
            filepath = output_dir / filename

            try:
                shutil.copy2(source_image, filepath)
                self._process_image(filepath)

                images.append(ImageSource(
                    url=str(source_image),
                    local_path=filepath,
                    source_type='placeholder',
                    alt_text=f"Image {offset + i + 1}"
                ))
            except Exception as e:
                logger.warning(f"Failed to copy placeholder image: {e}")

        return images

    def _extract_instagram_username(self, url: str) -> Optional[str]:
        """Extracts Instagram username from URL."""
        if not url:
            return None

        # Handle direct username
        if not url.startswith('http'):
            return url.lstrip('@')

        # Parse URL
        try:
            parsed = urlparse(url)
            path = parsed.path.strip('/')

            # Remove trailing slashes and get first path component
            username = path.split('/')[0]

            if username:
                return username
        except Exception:
            pass

        return None

    def _process_image(self, filepath: Path, max_size: int = 1200):
        """
        Processes image: converts to JPG, resizes if needed.
        """
        try:
            with Image.open(filepath) as img:
                # Convert to RGB if needed
                if img.mode in ('RGBA', 'P'):
                    img = img.convert('RGB')

                # Resize if too large
                if max(img.size) > max_size:
                    img.thumbnail((max_size, max_size), Image.Resampling.LANCZOS)

                # Save as JPG
                img.save(filepath, 'JPEG', quality=85)
        except Exception as e:
            logger.warning(f"Image processing failed for {filepath}: {e}")

    def close(self):
        """Cleanup resources."""
        self.session.close()


# =============================================================================
# SECTION 7: TEMPLATE CUSTOMIZATION FUNCTIONS
# =============================================================================

def sanitize_folder_name(name: str) -> str:
    """
    Converts a string to a safe folder name.
    """
    # Normalize unicode characters
    name = unicodedata.normalize('NFKD', name)
    name = name.encode('ASCII', 'ignore').decode('ASCII')

    # Replace spaces and special chars with underscores
    name = re.sub(r'[^\w\s-]', '', name)
    name = re.sub(r'[-\s]+', '_', name)

    # Remove leading/trailing underscores
    name = name.strip('_')

    return name or 'business'


def copy_template_to_output(
    template: Template,
    output_dir: Path
) -> Path:
    """
    Copies template to output directory.
    Skips node_modules if present.
    """
    proyecto_dir = output_dir / 'proyecto'

    def ignore_patterns(directory, files):
        """Returns files to ignore during copy."""
        ignore = []
        if 'node_modules' in files:
            ignore.append('node_modules')
        if '.git' in files:
            ignore.append('.git')
        return ignore

    if proyecto_dir.exists():
        shutil.rmtree(proyecto_dir)

    shutil.copytree(
        template.path,
        proyecto_dir,
        ignore=ignore_patterns
    )

    return proyecto_dir


def generate_site_config_content(
    content: GeneratedContent,
    design_decisions: DesignDecisions,
    lead: Lead,
    images: List[ImageSource]
) -> str:
    """
    Generates the complete site.config.ts content.
    """
    # Prepare image paths for config
    hero_image = "/images/hero.jpg"
    about_image = "/images/about.jpg"

    gallery_images = []
    for i, img in enumerate(images[2:8] if len(images) > 2 else images[:6]):  # Skip first 2 for hero/about
        gallery_images.append({
            "src": f"/images/gallery/{i + 1}.jpg",
            "alt": img.alt_text
        })

    # Format services
    services_str = json.dumps(content.services, ensure_ascii=False, indent=4)

    # Format badges
    badges_str = json.dumps(content.about_badges, ensure_ascii=False, indent=4)

    # Format gallery
    gallery_str = json.dumps(gallery_images, ensure_ascii=False, indent=6)

    # Format testimonials
    testimonials_str = json.dumps(content.testimonials, ensure_ascii=False, indent=4)

    # Format schedule
    schedule = content.contact_schedule or {
        "weekdays": "Lun - Vie: 10:00 - 20:00",
        "saturday": "Sábado: 10:00 - 18:00",
        "sunday": "Domingo: Cerrado"
    }

    # Extract WhatsApp number (digits only)
    whatsapp_number = re.sub(r'\D', '', lead.phone_whatsapp or '')
    if whatsapp_number.startswith('56'):
        pass  # Already has country code
    elif whatsapp_number.startswith('9'):
        whatsapp_number = '56' + whatsapp_number

    # Format phone for display
    phone_display = lead.phone_whatsapp or ''
    if phone_display and not phone_display.startswith('+'):
        if phone_display.startswith('56'):
            phone_display = '+' + phone_display
        elif phone_display.startswith('9'):
            phone_display = '+56 ' + phone_display

    config = f'''// ============================================
// CONFIGURACIÓN DEL SITIO - GENERADO AUTOMÁTICAMENTE
// ============================================
// Generado por Mockup Generator para: {content.business_name}
// Fecha: {datetime.now().strftime('%Y-%m-%d %H:%M')}

export const siteConfig = {{
  // ====== INFORMACIÓN BÁSICA ======
  businessName: "{content.business_name}",
  tagline: "{content.tagline}",
  description: "{content.description}",

  // ====== TEMA DE COLOR ======
  theme: '{design_decisions.theme}' as const,

  // ====== HERO SECTION ======
  hero: {{
    title: "{content.hero_title}",
    subtitle: "{content.hero_subtitle}",
    ctaPrimary: "{content.hero_cta_primary}",
    ctaSecondary: "{content.hero_cta_secondary}",
    image: "{hero_image}",
  }},

  // ====== SOBRE MÍ ======
  about: {{
    title: "{content.about_title}",
    name: "{content.about_name}",
    bio: "{content.about_bio}",
    image: "{about_image}",
    badges: {badges_str}
  }},

  // ====== SERVICIOS ======
  services: {services_str},

  // ====== GALERÍA ======
  gallery: {{
    title: "{content.gallery_title}",
    images: {gallery_str}
  }},

  // ====== TESTIMONIOS ======
  testimonials: {testimonials_str},

  // ====== CONTACTO ======
  contact: {{
    phone: "{phone_display}",
    whatsapp: "{whatsapp_number}",
    email: "contacto@{sanitize_folder_name(content.business_name).lower()}.cl",
    address: "{lead.comuna}, {lead.ciudad or lead.region}",
    location: {{
      lat: -33.4489,
      lng: -70.6693,
    }},
    schedule: {{
      weekdays: "{schedule.get('weekdays', 'Lun - Vie: 10:00 - 20:00')}",
      saturday: "{schedule.get('saturday', 'Sábado: 10:00 - 18:00')}",
      sunday: "{schedule.get('sunday', 'Domingo: Cerrado')}",
    }}
  }},

  // ====== REDES SOCIALES ======
  social: {{
    instagram: "{lead.instagram_fb_link or ''}",
    facebook: "",
    tiktok: "",
  }},

  // ====== SEO ======
  seo: {{
    keywords: "{content.seo_keywords}",
    ogImage: "/images/og-image.jpg",
  }}
}};

export type Theme = 'elegante' | 'fresh' | 'bold' | 'natural';
'''

    return config


def write_site_config(proyecto_dir: Path, config_content: str):
    """Writes site.config.ts to the proyecto directory."""
    config_path = proyecto_dir / 'src' / 'config' / 'site.config.ts'
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_content, encoding='utf-8')
    logger.info(f"Wrote site.config.ts to {config_path}")


def modify_index_astro(
    proyecto_dir: Path,
    sections_order: List[str],
    sections_to_hide: List[str]
):
    """
    Modifies index.astro to reorder sections and hide specified ones.
    """
    index_path = proyecto_dir / 'src' / 'pages' / 'index.astro'

    if not index_path.exists():
        logger.warning(f"index.astro not found at {index_path}")
        return

    content = index_path.read_text(encoding='utf-8')

    # Comment out imports for hidden sections
    for section in sections_to_hide:
        # Comment import line
        pattern = rf"^(import {section} from.*$)"
        content = re.sub(pattern, rf"// \1  // Hidden", content, flags=re.MULTILINE)

        # Comment component usage
        pattern = rf"(\s*)(<{section}\s*/?>)"
        content = re.sub(pattern, rf"\1{{/* \2 */}}  {{/* Hidden */}}", content)

    # Note: Reordering sections would require more complex AST manipulation
    # For now, we'll rely on the order being close enough to default
    # Future improvement: parse and rewrite the component section

    index_path.write_text(content, encoding='utf-8')
    logger.info(f"Modified index.astro: hidden sections = {sections_to_hide}")


def copy_images_to_public(
    proyecto_dir: Path,
    images: List[ImageSource]
):
    """
    Copies sourced images to the public/images folder.
    """
    public_images = proyecto_dir / 'public' / 'images'
    gallery_dir = public_images / 'gallery'

    public_images.mkdir(parents=True, exist_ok=True)
    gallery_dir.mkdir(parents=True, exist_ok=True)

    if not images:
        logger.warning("No images to copy")
        return

    # First image -> hero.jpg
    if len(images) >= 1:
        shutil.copy2(images[0].local_path, public_images / 'hero.jpg')

    # Second image -> about.jpg (or reuse hero)
    if len(images) >= 2:
        shutil.copy2(images[1].local_path, public_images / 'about.jpg')
    elif len(images) >= 1:
        shutil.copy2(images[0].local_path, public_images / 'about.jpg')

    # Remaining -> gallery
    gallery_images = images[2:] if len(images) > 2 else images
    for i, img in enumerate(gallery_images[:6]):
        dest = gallery_dir / f'{i + 1}.jpg'
        shutil.copy2(img.local_path, dest)

    logger.info(f"Copied {len(images)} images to public/images")


# =============================================================================
# SECTION 8: BUILD AND SCREENSHOT FUNCTIONS
# =============================================================================

class AstroServerManager:
    """Manages Astro dev server lifecycle."""

    def __init__(self, proyecto_dir: Path, port: int = DEFAULT_PORT):
        self.proyecto_dir = proyecto_dir
        self.port = port
        self.process: Optional[subprocess.Popen] = None

    def install_dependencies(self, timeout: int = NPM_INSTALL_TIMEOUT) -> bool:
        """
        Runs npm install in proyecto_dir.
        Returns True on success.
        """
        logger.info(f"Running npm install in {self.proyecto_dir}")

        try:
            result = subprocess.run(
                ['npm', 'install'],
                cwd=self.proyecto_dir,
                capture_output=True,
                text=True,
                timeout=timeout
            )

            if result.returncode != 0:
                logger.error(f"npm install failed: {result.stderr}")
                return False

            logger.info("npm install completed successfully")
            return True

        except subprocess.TimeoutExpired:
            logger.error(f"npm install timed out after {timeout}s")
            return False
        except Exception as e:
            logger.error(f"npm install error: {e}")
            return False

    def start_server(self, timeout: int = SERVER_START_TIMEOUT) -> bool:
        """
        Starts Astro dev server and waits for it to be ready.
        Returns True when ready.
        """
        logger.info(f"Starting Astro dev server on port {self.port}")

        try:
            # Start the process
            self.process = subprocess.Popen(
                ['npm', 'run', 'dev', '--', '--port', str(self.port)],
                cwd=self.proyecto_dir,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                start_new_session=True  # Create new process group
            )

            # Wait for server to be ready
            return self.wait_for_server_ready(timeout)

        except Exception as e:
            logger.error(f"Failed to start Astro server: {e}")
            return False

    def wait_for_server_ready(self, timeout: int = SERVER_START_TIMEOUT) -> bool:
        """
        Polls localhost until server responds with 200.
        """
        url = f"http://localhost:{self.port}"
        start_time = time.time()
        delay = 0.5

        while time.time() - start_time < timeout:
            try:
                with httpx.Client(timeout=5.0) as client:
                    response = client.get(url)
                    if response.status_code == 200:
                        logger.info(f"Server ready at {url}")
                        return True
            except Exception:
                pass

            time.sleep(delay)
            delay = min(delay * 1.5, 5.0)  # Exponential backoff, max 5s

        logger.error(f"Server failed to start within {timeout}s")
        return False

    def stop_server(self):
        """
        Stops the Astro server and cleans up processes.
        """
        if self.process:
            try:
                # Try graceful termination first
                os.killpg(os.getpgid(self.process.pid), signal.SIGTERM)
                self.process.wait(timeout=5)
            except Exception:
                try:
                    # Force kill if needed
                    os.killpg(os.getpgid(self.process.pid), signal.SIGKILL)
                except Exception:
                    pass

            self.process = None

        # Also kill any process on the port (safety cleanup)
        self._kill_process_on_port(self.port)

        logger.info("Astro server stopped")

    def _kill_process_on_port(self, port: int):
        """Kills any process using the specified port."""
        try:
            for proc in psutil.process_iter(['pid', 'name', 'connections']):
                try:
                    for conn in proc.connections():
                        if conn.laddr.port == port:
                            proc.kill()
                            logger.debug(f"Killed process {proc.pid} on port {port}")
                except (psutil.NoSuchProcess, psutil.AccessDenied):
                    pass
        except Exception as e:
            logger.debug(f"Error killing process on port: {e}")

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.stop_server()


async def take_screenshot(
    url: str,
    output_path: Path,
    viewport_width: int = 1440,
    viewport_height: int = 900,
    wait_time: int = SCREENSHOT_WAIT
) -> bool:
    """
    Takes a screenshot using Playwright.
    Only captures the visible viewport (hero section).
    """
    try:
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)

            page = await browser.new_page(
                viewport={'width': viewport_width, 'height': viewport_height}
            )

            # Navigate and wait for content
            await page.goto(url, wait_until='networkidle', timeout=30000)

            # Additional wait for any animations
            await page.wait_for_timeout(wait_time)

            # Take screenshot of viewport only (hero section)
            await page.screenshot(path=str(output_path), full_page=False)

            await browser.close()

            logger.info(f"Screenshot saved to {output_path}")
            return True

    except Exception as e:
        logger.error(f"Screenshot failed: {e}")
        return False


# =============================================================================
# SECTION 9: EXCEL OPERATIONS
# =============================================================================

def load_leads_from_excel(excel_path: Path) -> List[Lead]:
    """
    Reads Excel file and returns list of leads to process.
    Filters for Tier 1 leads that haven't been processed yet.
    """
    try:
        df = pd.read_excel(excel_path, engine='openpyxl')

        # Standardize column names (handle variations)
        column_mapping = {
            'Business Name': 'business_name',
            'Niche': 'niche',
            'País': 'pais',
            'Región': 'region',
            'Ciudad': 'ciudad',
            'Comuna': 'comuna',
            'Website URL': 'website_url',
            'Phone/WhatsApp': 'phone_whatsapp',
            'Instagram/FB Link': 'instagram_fb_link',
            'Status': 'status',
            'Tech Flaw': 'tech_flaw',
            'Owner Name': 'owner_name',
            'Tier': 'tier',
            'Source Query': 'source_query',
            'Generate Mockup': 'generate_mockup',
            'Mockup Status': 'mockup_status',
            'Mockup Path': 'mockup_path',
            'Mockup Date': 'mockup_date',
        }

        # Rename columns that exist
        df = df.rename(columns={k: v for k, v in column_mapping.items() if k in df.columns})

        # Fill missing columns with empty strings
        for col in column_mapping.values():
            if col not in df.columns:
                df[col] = ''

        # Filter leads
        # 1. Tier 1 (no website)
        # 2. Generate Mockup = 'Yes' or empty
        # 3. Mockup Status is not 'Completed'

        mask = (
            (df['tier'].str.contains('Tier 1', case=False, na=False) | (df['tier'] == '')) &
            (df['generate_mockup'].str.lower().isin(['yes', 'si', 'sí', '']) | df['generate_mockup'].isna()) &
            (~df['mockup_status'].str.lower().isin(['completed', 'completado']))
        )

        filtered_df = df[mask].copy()

        leads = []
        for idx, row in filtered_df.iterrows():
            lead = Lead(
                business_name=str(row.get('business_name', '')).strip(),
                niche=str(row.get('niche', '')).strip(),
                pais=str(row.get('pais', 'Chile')).strip(),
                region=str(row.get('region', '')).strip(),
                ciudad=str(row.get('ciudad', '')).strip(),
                comuna=str(row.get('comuna', '')).strip(),
                website_url=str(row.get('website_url', '')).strip(),
                phone_whatsapp=str(row.get('phone_whatsapp', '')).strip(),
                instagram_fb_link=str(row.get('instagram_fb_link', '')).strip(),
                status=str(row.get('status', '')).strip(),
                tech_flaw=str(row.get('tech_flaw', '')).strip(),
                owner_name=str(row.get('owner_name', '')).strip(),
                tier=str(row.get('tier', '')).strip(),
                source_query=str(row.get('source_query', '')).strip(),
                generate_mockup=str(row.get('generate_mockup', '')).strip(),
                mockup_status=str(row.get('mockup_status', '')).strip(),
                mockup_path=str(row.get('mockup_path', '')).strip(),
                mockup_date=row.get('mockup_date') if pd.notna(row.get('mockup_date')) else None,
                row_index=idx
            )

            # Skip if no business name
            if lead.business_name:
                leads.append(lead)

        logger.info(f"Loaded {len(leads)} leads to process from Excel")
        return leads

    except Exception as e:
        logger.error(f"Failed to load Excel file: {e}")
        raise


def update_lead_status(
    excel_path: Path,
    row_index: int,
    status: str,
    mockup_path: Optional[str] = None,
    mockup_date: Optional[datetime] = None
):
    """
    Updates a single lead's status in the Excel file.
    """
    try:
        # Read with openpyxl to preserve formatting
        from openpyxl import load_workbook

        wb = load_workbook(excel_path)
        ws = wb.active

        # Find column indices (1-indexed)
        header_row = 1
        headers = {cell.value: cell.column for cell in ws[header_row]}

        # Excel row is index + 2 (1 for 0-indexing, 1 for header)
        excel_row = row_index + 2

        # Update Mockup Status
        if 'Mockup Status' in headers:
            ws.cell(row=excel_row, column=headers['Mockup Status'], value=status)

        # Update Mockup Path
        if mockup_path and 'Mockup Path' in headers:
            ws.cell(row=excel_row, column=headers['Mockup Path'], value=mockup_path)

        # Update Mockup Date
        if mockup_date and 'Mockup Date' in headers:
            ws.cell(row=excel_row, column=headers['Mockup Date'], value=mockup_date)

        wb.save(excel_path)
        logger.debug(f"Updated Excel row {excel_row}: status={status}")

    except Exception as e:
        logger.error(f"Failed to update Excel: {e}")


# =============================================================================
# SECTION 9.5: PARALLEL PROCESSOR
# =============================================================================

class ParallelProcessor:
    """
    Handles parallel processing of multiple leads with thread-safe operations.
    Each worker gets a unique port for its Astro server.
    """

    def __init__(self, max_workers: int = DEFAULT_WORKERS):
        self.max_workers = min(max_workers, MAX_WORKERS)
        self.executor = ThreadPoolExecutor(max_workers=self.max_workers)
        self.port_pool: Queue = Queue()
        self.excel_lock = Lock()
        self.api_semaphore = Semaphore(5)  # Rate limiting for API calls

        # Initialize port pool
        for port in PORT_POOL[:self.max_workers]:
            self.port_pool.put(port)

        logger.info(f"ParallelProcessor initialized with {self.max_workers} workers")

    def process_leads_parallel(
        self,
        leads: List[Lead],
        templates: Dict[str, List[Template]],
        output_folder: Path,
        claude_client: anthropic.Anthropic,
        excel_path: Path
    ) -> List[ProcessingResult]:
        """
        Processes multiple leads in parallel using thread pool.
        Returns list of ProcessingResults.
        """
        results: List[ProcessingResult] = []
        futures = []

        # Submit all leads to the executor
        for lead in leads:
            future = self.executor.submit(
                self._process_lead_worker,
                lead,
                templates,
                output_folder,
                claude_client,
                excel_path
            )
            futures.append((future, lead))

        # Collect results with progress bar
        with tqdm(total=len(leads), desc="Procesando leads", unit="lead") as pbar:
            for future, lead in futures:
                try:
                    result = future.result()
                    results.append(result)
                    status = "✓" if result.success else "✗"
                    pbar.set_postfix_str(f"{status} {lead.business_name[:20]}")
                except Exception as e:
                    logger.error(f"Worker failed for {lead.business_name}: {e}")
                    results.append(ProcessingResult(
                        success=False,
                        lead=lead,
                        error_message=str(e)
                    ))
                finally:
                    pbar.update(1)

        return results

    def _process_lead_worker(
        self,
        lead: Lead,
        templates: Dict[str, List[Template]],
        output_folder: Path,
        claude_client: anthropic.Anthropic,
        excel_path: Path
    ) -> ProcessingResult:
        """
        Worker function that processes a single lead.
        Acquires a port from the pool and releases it when done.
        """
        port = self.port_pool.get()  # Blocks until a port is available
        try:
            # Create a dedicated image sourcer for this worker
            image_sourcer = ImageSourcer(
                fallback_folder=Path(__file__).parent / 'fallback_images'
            )

            try:
                result = process_single_lead(
                    lead=lead,
                    templates=templates,
                    output_folder=output_folder,
                    claude_client=claude_client,
                    image_sourcer=image_sourcer,
                    excel_path=excel_path,
                    port=port,
                    excel_lock=self.excel_lock
                )
            finally:
                image_sourcer.close()

            return result
        finally:
            self.port_pool.put(port)  # Return port to pool

    def shutdown(self):
        """Cleans up the executor."""
        self.executor.shutdown(wait=True)
        logger.info("ParallelProcessor shutdown complete")


# =============================================================================
# SECTION 10: MAIN ORCHESTRATION
# =============================================================================

def save_outreach_messages(output_dir: Path, messages: Dict[str, str]):
    """Saves outreach messages to mensaje.txt."""
    mensaje_path = output_dir / 'mensaje.txt'

    content = f"""=== MENSAJE WHATSAPP ===

{messages.get('whatsapp', '')}

=== MENSAJE EMAIL ===

{messages.get('email', '')}
"""

    mensaje_path.write_text(content, encoding='utf-8')
    logger.info(f"Saved messages to {mensaje_path}")


def save_metadata(
    output_dir: Path,
    lead: Lead,
    design_decisions: DesignDecisions,
    content: GeneratedContent,
    images: List[ImageSource]
):
    """Saves processing metadata to info.json."""
    info_path = output_dir / 'info.json'

    metadata = {
        'lead': {
            'business_name': lead.business_name,
            'owner_name': lead.owner_name,
            'niche': lead.niche,
            'location': {
                'comuna': lead.comuna,
                'ciudad': lead.ciudad,
                'region': lead.region,
                'pais': lead.pais
            },
            'contact': {
                'phone': lead.phone_whatsapp,
                'instagram': lead.instagram_fb_link
            }
        },
        'design_decisions': {
            'template': design_decisions.template_name,
            'theme': design_decisions.theme,
            'sections_order': design_decisions.sections_order,
            'sections_hidden': design_decisions.sections_to_hide
        },
        'content_summary': {
            'tagline': content.tagline,
            'services_count': len(content.services),
            'has_testimonials': len(content.testimonials) > 0
        },
        'images': {
            'count': len(images),
            'sources': list(set(img.source_type for img in images))
        },
        'generated_at': datetime.now().isoformat(),
        'generator_version': '1.0.0'
    }

    with open(info_path, 'w', encoding='utf-8') as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)

    logger.info(f"Saved metadata to {info_path}")


def process_single_lead(
    lead: Lead,
    templates: Dict[str, List[Template]],
    output_folder: Path,
    claude_client: anthropic.Anthropic,
    image_sourcer: ImageSourcer,
    excel_path: Path,
    port: int = DEFAULT_PORT,
    excel_lock: Optional[Lock] = None
) -> ProcessingResult:
    """
    Full processing pipeline for a single lead.

    Args:
        port: Port number for Astro server (default 4321)
        excel_lock: Thread lock for Excel writes (optional, for parallel processing)
    """
    logger.info(f"{'='*60}")
    logger.info(f"Processing: {lead.business_name} (port {port})")
    logger.info(f"{'='*60}")

    # Create output directory
    comuna_folder = sanitize_folder_name(lead.comuna) or 'Sin_Comuna'
    business_folder = sanitize_folder_name(lead.business_name)
    output_dir = output_folder / comuna_folder / business_folder

    def safe_update_excel(row_index: int, status: str, mockup_path: Optional[str] = None, mockup_date: Optional[datetime] = None):
        """Thread-safe Excel update."""
        if excel_lock:
            with excel_lock:
                update_lead_status(excel_path, row_index, status, mockup_path, mockup_date)
        else:
            update_lead_status(excel_path, row_index, status, mockup_path, mockup_date)

    try:
        # 1. Update Excel to Processing
        safe_update_excel(lead.row_index, 'Processing')

        # 2. Get templates for niche
        niche_templates = templates.get(lead.niche, [])
        if not niche_templates:
            # Try to find any available templates
            for niche, tmpl_list in templates.items():
                if tmpl_list:
                    niche_templates = tmpl_list
                    logger.warning(f"No templates for niche '{lead.niche}', using '{niche}'")
                    break

        if not niche_templates:
            raise ValueError("No templates available")

        # 3. Get design decisions from Claude
        logger.info("Getting design decisions from Claude...")
        design_decisions = choose_design_decisions(
            claude_client,
            lead,
            niche_templates
        )
        logger.info(f"Design: template={design_decisions.template_name}, theme={design_decisions.theme}")

        # 4. Source images
        logger.info("Sourcing images...")
        output_dir.mkdir(parents=True, exist_ok=True)
        images = image_sourcer.source_images_for_lead(lead, output_dir)
        logger.info(f"Sourced {len(images)} images")

        # 5. Generate content with Claude
        logger.info("Generating personalized content...")
        content = generate_personalized_content(
            claude_client,
            lead,
            design_decisions
        )

        # 6. Find selected template
        selected_template = next(
            (t for t in niche_templates if t.name == design_decisions.template_name),
            niche_templates[0]
        )

        # 7. Copy template
        logger.info(f"Copying template {selected_template.name}...")
        proyecto_dir = copy_template_to_output(selected_template, output_dir)

        # 8. Generate and write site.config.ts
        logger.info("Generating site.config.ts...")
        config_content = generate_site_config_content(
            content, design_decisions, lead, images
        )
        write_site_config(proyecto_dir, config_content)

        # 9. Modify index.astro
        logger.info("Modifying index.astro...")
        modify_index_astro(
            proyecto_dir,
            design_decisions.sections_order,
            design_decisions.sections_to_hide
        )

        # 10. Copy images to public
        logger.info("Copying images to public folder...")
        copy_images_to_public(proyecto_dir, images)

        # 11-15. Build and screenshot
        with AstroServerManager(proyecto_dir, port=port) as server:
            # 11. npm install
            logger.info("Installing dependencies...")
            if not server.install_dependencies():
                raise RuntimeError("npm install failed")

            # 12. Start server
            logger.info("Starting Astro server...")
            if not server.start_server():
                raise RuntimeError("Failed to start Astro server")

            # 13-14. Take screenshot
            logger.info("Taking screenshot...")
            mockup_path = output_dir / 'mockup.png'
            screenshot_success = asyncio.run(
                take_screenshot(
                    f"http://localhost:{server.port}",
                    mockup_path
                )
            )

            if not screenshot_success:
                raise RuntimeError("Screenshot failed")

        # 16. Generate outreach messages
        logger.info("Generating outreach messages...")
        messages = generate_outreach_messages(
            claude_client,
            lead,
            'mockup.png'
        )

        # 17. Save outputs
        save_outreach_messages(output_dir, messages)
        save_metadata(output_dir, lead, design_decisions, content, images)

        # 18. Update Excel to Completed
        safe_update_excel(
            lead.row_index,
            'Completed',
            str(output_dir),
            datetime.now()
        )

        logger.info(f"Successfully processed: {lead.business_name}")

        return ProcessingResult(
            success=True,
            lead=lead,
            output_path=output_dir
        )

    except Exception as e:
        logger.error(f"Failed to process {lead.business_name}: {e}")

        # Update Excel with failure
        safe_update_excel(
            lead.row_index,
            f'Failed: {str(e)[:100]}'
        )

        return ProcessingResult(
            success=False,
            lead=lead,
            error_message=str(e)
        )


def print_summary(results: List[ProcessingResult]):
    """Prints processing summary."""
    successful = [r for r in results if r.success]
    failed = [r for r in results if not r.success]

    print("\n" + "="*60)
    print("RESUMEN DE PROCESAMIENTO")
    print("="*60)
    print(f"Total procesados: {len(results)}")
    print(f"Exitosos: {len(successful)}")
    print(f"Fallidos: {len(failed)}")

    if successful:
        print("\n✅ Exitosos:")
        for r in successful:
            print(f"  - {r.lead.business_name}: {r.output_path}")

    if failed:
        print("\n❌ Fallidos:")
        for r in failed:
            print(f"  - {r.lead.business_name}: {r.error_message}")

    print("="*60)


def main():
    """Main entry point."""
    print("="*60)
    print("MOCKUP GENERATOR")
    print("Generador de mockups personalizados para leads")
    print("="*60)

    # 1. Select Excel file
    print("\n1. Selecciona el archivo Excel con los leads...")
    excel_path = select_excel_file()
    if not excel_path:
        print("Cancelado: No se seleccionó archivo Excel")
        return
    print(f"   Excel: {excel_path}")

    # 2. Select templates folder
    print("\n2. Selecciona la carpeta de templates...")
    templates_folder = select_templates_folder()
    if not templates_folder:
        print("Cancelado: No se seleccionó carpeta de templates")
        return
    print(f"   Templates: {templates_folder}")

    # 3. Select output folder
    print("\n3. Selecciona la carpeta de salida...")
    output_folder = select_output_folder()
    if not output_folder:
        print("Cancelado: No se seleccionó carpeta de salida")
        return
    print(f"   Output: {output_folder}")

    # 4. Discover templates
    print("\n4. Descubriendo templates...")
    templates = discover_templates(templates_folder)

    total_templates = sum(len(t) for t in templates.values())
    if total_templates == 0:
        show_error("No se encontraron templates válidos en la carpeta seleccionada")
        return

    print(f"   Encontrados {total_templates} templates en {len(templates)} nichos:")
    for niche, tmpls in templates.items():
        print(f"   - {niche}: {len(tmpls)} templates")

    # 5. Load leads
    print("\n5. Cargando leads del Excel...")
    try:
        leads = load_leads_from_excel(excel_path)
    except Exception as e:
        show_error(f"Error al cargar Excel: {e}")
        return

    if not leads:
        show_info("No hay leads pendientes para procesar")
        return

    print(f"   {len(leads)} leads pendientes para procesar")

    # 6. Initialize Claude client
    print("\n6. Inicializando cliente Claude API...")
    try:
        claude_client = create_claude_client()
        print("   Cliente inicializado correctamente")
    except EnvironmentError as e:
        show_error(str(e))
        return

    # 7. Show configuration dialog
    print("\n7. Mostrando configuración...")
    config = show_config_dialog(len(leads), total_templates, output_folder)

    if not config:
        print("Cancelado por el usuario")
        return

    print(f"   Workers: {config.num_workers}")
    print(f"   Paralelo: {'Sí' if config.use_parallel else 'No'}")

    # 8. Process leads
    print("\n8. Procesando leads...")

    if config.use_parallel and config.num_workers > 1:
        # Parallel processing
        print(f"   Modo: Paralelo con {config.num_workers} workers")
        processor = ParallelProcessor(max_workers=config.num_workers)

        try:
            results = processor.process_leads_parallel(
                leads=leads,
                templates=templates,
                output_folder=output_folder,
                claude_client=claude_client,
                excel_path=excel_path
            )
        finally:
            processor.shutdown()
    else:
        # Sequential processing
        print("   Modo: Secuencial")
        results: List[ProcessingResult] = []

        # Initialize image sourcer for sequential mode
        image_sourcer = ImageSourcer(
            fallback_folder=Path(__file__).parent / 'fallback_images'
        )

        try:
            for i, lead in enumerate(leads, 1):
                print(f"\n[{i}/{len(leads)}] Procesando: {lead.business_name}")

                result = process_single_lead(
                    lead,
                    templates,
                    output_folder,
                    claude_client,
                    image_sourcer,
                    excel_path
                )

                results.append(result)

                # Small delay between leads to avoid rate limits
                if i < len(leads):
                    time.sleep(2)
        finally:
            image_sourcer.close()

    # 11. Print summary
    print_summary(results)

    # 12. Show completion message
    successful_count = len([r for r in results if r.success])
    show_info(
        f"Procesamiento completado.\n\n"
        f"Exitosos: {successful_count}/{len(results)}\n"
        f"Revisa la carpeta: {output_folder}"
    )


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nProceso interrumpido por el usuario")
        sys.exit(1)
    except Exception as e:
        logger.exception("Error fatal")
        show_error(f"Error fatal: {e}")
        sys.exit(1)
